# STAGE 1: Build React App
FROM node:20-alpine AS builder

RUN apk add --no-cache libc6-compat python3 make g++

WORKDIR /app

COPY package*.json ./

RUN npm install --include=optional

COPY . .

RUN npm install @tailwindcss/oxide-linux-x64-musl --save-dev

RUN npm run build

# STAGE 2: Serve Using Nginx
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]